name: LevelIsBorder
version: '${project.version}'
main: com.jannis.levelisborder.LevelIsBorder
api-version: 1.17
depend:
  - WorldBorderAPI
authors: [ Jannis ]
description: The Player Levels are the size of the border
commands:
  border:
    description: You can edit the border size with /border size <size>. To set the center type /border center <x> <z>. With /reload, you can refresh the border.
    usage: /border command <number> (<number2>)
